use std::fs;
use std::io::{self, Write};

use turbovec::codebook;
use turbovec::TurboQuantIndex;

const DIM: usize = 128;
const N_DB: usize = 8;
const N_QUERY: usize = 3;
const K: usize = 3;

fn normalize_rows(values: &mut [f32], dim: usize) {
    for row in values.chunks_exact_mut(dim) {
        let norm = row.iter().map(|v| (*v as f64) * (*v as f64)).sum::<f64>().sqrt();
        if norm > 0.0 {
            for value in row {
                *value = (*value as f64 / norm) as f32;
            }
        }
    }
}

fn fill_value(row: usize, col: usize, phase: f64) -> f32 {
    let x = (row + 1) as f64;
    let y = (col + 1) as f64;
    (0.63 * (0.017 * x * y + phase).sin()
        + 0.31 * (0.041 * (x + 3.0) * (y + 1.0)).cos()
        + 0.06 * (0.097 * (x + y)).sin()) as f32
}

fn print_f32_array(name: &str, values: &[f32]) {
    println!("static const float {}[] = {{", name);
    for chunk in values.chunks(8) {
        print!("   ");
        for value in chunk {
            print!(" {:.9e}f,", value);
        }
        println!();
    }
    println!("}};");
}

fn print_u8_array(name: &str, values: &[u8]) {
    println!("static const uint8_t {}[] = {{", name);
    for chunk in values.chunks(16) {
        print!("   ");
        for value in chunk {
            print!(" 0x{:02x},", value);
        }
        println!();
    }
    println!("}};");
}

fn read_u32_le(bytes: &[u8]) -> u32 {
    u32::from_le_bytes(bytes.try_into().unwrap())
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let bits = args.get(1).map(|s| s.parse::<usize>().unwrap()).unwrap_or(4);
    assert!(bits == 2 || bits == 4);
    let prefix = if bits == 2 { "kTurboVecGoldenQ2" } else { "kTurboVecGolden" };

    let mut db = vec![0.0f32; N_DB * DIM];
    let mut queries = vec![0.0f32; N_QUERY * DIM];
    for row in 0..N_DB {
        for col in 0..DIM {
            db[row * DIM + col] = fill_value(row, col, 0.13);
        }
    }
    for row in 0..N_QUERY {
        for col in 0..DIM {
            queries[row * DIM + col] = fill_value(row * 2, col, 0.29);
        }
    }
    normalize_rows(&mut db, DIM);
    normalize_rows(&mut queries, DIM);

    let mut index = TurboQuantIndex::new(DIM, bits).unwrap();
    index.add(&db);
    index.prepare();
    let results = index.search(&queries, K);
    let (_, centroids) = codebook::codebook(bits, DIM);
    let tv_path = std::env::current_dir()
        .unwrap()
        .join(format!("tests/turbovec-golden-gen/turbovec-q{}.tmp.tv", bits));
    index.write(&tv_path).unwrap();
    let tv_bytes = fs::read(&tv_path).unwrap();
    fs::remove_file(&tv_path).unwrap();

    let core_offset = 5;
    assert_eq!(&tv_bytes[0..4], b"TVPI");
    assert_eq!(tv_bytes[4], 3);
    assert_eq!(tv_bytes[core_offset], bits as u8);
    assert_eq!(read_u32_le(&tv_bytes[core_offset + 1..core_offset + 5]) as usize, DIM);
    assert_eq!(read_u32_le(&tv_bytes[core_offset + 5..core_offset + 9]) as usize, N_DB);
    let packed_offset = core_offset + 9;
    let packed_len = N_DB * bits * (DIM / 8);
    let scales_offset = packed_offset + packed_len;
    let scales_len = N_DB;
    let calib_count_offset = scales_offset + scales_len * 4;
    let calib_count = read_u32_le(&tv_bytes[calib_count_offset..calib_count_offset + 4]) as usize;
    let packed_codes = &tv_bytes[packed_offset..packed_offset + packed_len];
    let scale_bytes = &tv_bytes[scales_offset..scales_offset + scales_len * 4];
    let rust_scales: Vec<f32> = scale_bytes
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes(b.try_into().unwrap()))
        .collect();

    println!("// Generated by tests/turbovec-golden-gen with turbovec 0.9, bits={}.", bits);
    print!("// Rust centroids:");
    for centroid in centroids {
        print!(" {:.9e}", centroid);
    }
    println!();
    println!("static constexpr int {}Dim = {};", prefix, DIM);
    println!("static constexpr int {}NDb = {};", prefix, N_DB);
    println!("static constexpr int {}NQuery = {};", prefix, N_QUERY);
    println!("static constexpr int {}K = {};", prefix, K);
    println!("static constexpr int {}RustTvVersion = 3;", prefix);
    println!("static constexpr int {}RustPackedBytes = {};", prefix, packed_len);
    println!("static constexpr int {}RustScaleCount = {};", prefix, scales_len);
    println!("static constexpr int {}RustCalibCount = {};", prefix, calib_count);
    println!("static constexpr int {}RustTvBytesLen = {};", prefix, tv_bytes.len());
    print_f32_array(&format!("{}Db", prefix), &db);
    print_f32_array(&format!("{}Queries", prefix), &queries);
    print_f32_array(&format!("{}RustScores", prefix), &results.scores);
    print_f32_array(&format!("{}RustScales", prefix), &rust_scales);
    print_u8_array(&format!("{}RustPackedCodes", prefix), packed_codes);
    print_u8_array(&format!("{}RustTvBytes", prefix), &tv_bytes);
    println!("static const int {}TopK[] = {{", prefix);
    for qi in 0..N_QUERY {
        print!("   ");
        for index in results.indices_for_query(qi) {
            print!(" {},", index);
        }
        println!();
    }
    println!("}};");

    io::stdout().flush().unwrap();
}
